export const ERROR = {
  MALFORMED_HANDOVER_MESSAGE: "MALFORMED_HANDOVER_MESSAGE",
  INVALID_HANDOVER_CODE: "INVALID_HANDOVER_CODE",
  MISSING_PENDING_REQUEST: "MISSING_PENDING_REQUEST",
  REQUEST_EXPIRED: "REQUEST_EXPIRED",
  REQUEST_NOT_PENDING: "REQUEST_NOT_PENDING",
  DECRYPTION_FAILED: "DECRYPTION_FAILED",
  TOO_MANY_FAILURES: "TOO_MANY_FAILURES",
} as const;

export type ErrorCode = (typeof ERROR)[keyof typeof ERROR];
