import { writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Effect, Layer } from 'effect';
import { describe, expect, it, vi } from 'vitest';
import { accountImport } from '../../src/commands/account/import.js';
import { decryptLegacyKeystore } from '../../src/services/legacy-keystore.js';
import { Output } from '../../src/services/output.js';
import { Prompt } from '../../src/services/prompt.js';
import { AccountStore } from '../../src/services/storage/account.js';

// Generated by the original Rust fastset-multisig CLI from the synthetic seed 0x01...01.
const legacy = {
  address: 'fast132yw8ht5p8cetl2jmvknewjawt9xwzdlrk2pyxlnwjyqrdq0dawqkehkfr',
  crypto: {
    cipher: 'aes-256-gcm',
    kdf: 'argon2id',
    kdf_params: { m_cost: 65536, t_cost: 3, p_cost: 1 },
    salt: 'faed9d97afb2a4d608753b3f8ad3ea6d',
    nonce: '7a91721e8dfb7c6e0f52f466',
    ciphertext: '8bf43d8746d6e0962b0e545942dec17aa8594b4c8a4ad860292e6d620ec391dd3ce29c084c3436914627726c12aac9ba7d50c9d027989c2cad8e377a8c6c',
  },
};
const password = 'synthetic test password';

describe('legacy multisig CLI keystore import', () => {
  it('decrypts a Rust-generated keystore and checks its Fast address', async () => {
    expect(await decryptLegacyKeystore(legacy, password)).toEqual(new Uint8Array(32).fill(1));
  }, 15_000);

  it('rejects wrong passwords, changed addresses, and unsupported KDF parameters', async () => {
    await expect(decryptLegacyKeystore(legacy, 'wrong')).rejects.toThrow();
    await expect(decryptLegacyKeystore({ ...legacy, address: 'fast1wrong' }, password)).rejects.toThrow();
    await expect(
      decryptLegacyKeystore({ ...legacy, crypto: { ...legacy.crypto, kdf_params: { ...legacy.crypto.kdf_params, m_cost: 2 ** 30 } } }, password),
    ).rejects.toThrow();
  }, 15_000);

  it('requires a password and passes it to account storage', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'fast-legacy-import-'));
    const path = join(dir, 'legacy.json');
    writeFileSync(path, JSON.stringify(legacy));
    const importAccount = vi.fn((name: string, seed: Uint8Array, pwd: string | null) => {
      expect(name).toBe('my-signer');
      expect(seed).toEqual(new Uint8Array(32).fill(1));
      expect(pwd).toBe(password);
      return Effect.succeed({ name, fastAddress: legacy.address, evmAddress: '0x00', encrypted: true });
    });
    const requiredPassword = vi.fn(() => Effect.succeed(password));
    const layer = Layer.mergeAll(
      Layer.succeed(AccountStore, { import: importAccount } as never),
      Layer.succeed(Prompt, { password: requiredPassword } as never),
      Layer.succeed(Output, { humanLine: () => Effect.void, ok: () => Effect.void } as never),
    );
    try {
      await Effect.runPromise(accountImport.handler({ name: 'my-signer', legacyKeystore: path } as never).pipe(Effect.provide(layer)));
      expect(requiredPassword).toHaveBeenCalledWith();
      expect(importAccount).toHaveBeenCalledOnce();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  }, 15_000);

  it('never stores an account after a wrong password or conflicting source flags', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'fast-legacy-import-'));
    const path = join(dir, 'legacy.json');
    writeFileSync(path, JSON.stringify(legacy));
    const importAccount = vi.fn(() => Effect.die('must not store'));
    const passwordPrompt = vi.fn(() => Effect.succeed('wrong'));
    const layer = Layer.mergeAll(
      Layer.succeed(AccountStore, { import: importAccount } as never),
      Layer.succeed(Prompt, { password: passwordPrompt } as never),
      Layer.succeed(Output, { humanLine: () => Effect.void, ok: () => Effect.void } as never),
    );
    try {
      const run = (args: object) => Effect.runPromise(accountImport.handler(args as never).pipe(Effect.provide(layer)));
      await expect(run({ name: 'my-signer', legacyKeystore: path, privateKey: '01' })).rejects.toThrow();
      expect(passwordPrompt).not.toHaveBeenCalled();
      await expect(run({ name: 'my-signer', legacyKeystore: path })).rejects.toThrow();
      passwordPrompt.mockReturnValueOnce(Effect.succeed(''));
      await expect(run({ name: 'my-signer', legacyKeystore: path })).rejects.toThrow();
      expect(importAccount).not.toHaveBeenCalled();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  }, 15_000);

  it('rejects an empty private-key flag alongside a legacy keystore before prompting', async () => {
    const importAccount = vi.fn(() => Effect.die('must not store'));
    const passwordPrompt = vi.fn(() => Effect.die('must not prompt'));
    const layer = Layer.mergeAll(
      Layer.succeed(AccountStore, { import: importAccount } as never),
      Layer.succeed(Prompt, { password: passwordPrompt } as never),
      Layer.succeed(Output, { humanLine: () => Effect.void, ok: () => Effect.void } as never),
    );

    await expect(
      Effect.runPromise(accountImport.handler({
        name: 'my-signer',
        privateKey: '',
        legacyKeystore: 'unused.json',
      } as never).pipe(Effect.provide(layer))),
    ).rejects.toThrow('Provide exactly one of --private-key, --key-file or --legacy-keystore');
    expect(passwordPrompt).not.toHaveBeenCalled();
    expect(importAccount).not.toHaveBeenCalled();
  });

  it('rejects an empty private-key flag as an invalid key rather than selecting a different source', async () => {
    const importAccount = vi.fn(() => Effect.die('must not store'));
    const passwordPrompt = vi.fn(() => Effect.die('must not prompt'));
    const layer = Layer.mergeAll(
      Layer.succeed(AccountStore, { import: importAccount } as never),
      Layer.succeed(Prompt, { password: passwordPrompt } as never),
      Layer.succeed(Output, { humanLine: () => Effect.void, ok: () => Effect.void } as never),
    );

    await expect(
      Effect.runPromise(accountImport.handler({ name: 'my-signer', privateKey: '' } as never).pipe(Effect.provide(layer))),
    ).rejects.toThrow('Private key must be exactly 32 bytes');
    expect(passwordPrompt).not.toHaveBeenCalled();
    expect(importAccount).not.toHaveBeenCalled();
  });
});
